#!/usr/bin/zsh

# Deploy the jobs into the system!
#
# This is so dumb, it just replaces the WHOLE user crontab each time.
# It also literally COPIES the jobs to a dir so that those are tied to the crontab
# 
# One day, i oughtta make this a commit hook or CI thing.

HERE=`dirname $0`

cd $HERE;                                                # Enter the jobs dir first
rm -rf deployed;                                         # nix the old deployment
mkdir deployed;
cp -rf {jobs,run,.python-version,.env} $HERE/deployed    # copy necessary files
crontab < jobs.crontab;                                  # deploy the crontab

echo 'Deployed!'