#!/usr/bin/zsh

# Run a python job within the jobs environment.

# set up zsh
source $HOME/.zshrc

# Enter the jobs dir
DIR=`dirname $0`
cd $DIR; 

# export env vars
set -o allexport
source .env
set +o allexport

# set up pyenv
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"

pyenv activate "$(cat .python-version)";
python $@