#!/usr/bin/zsh

# Run a python job within the jobs environment.

PYENV_NAME="$(cat .python-version)"
DIR=`dirname $0`

# env vars
set -o allexport
[[ -f .env ]] && source .env
set +o allexport

# set up pyenv
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"
pyenv activate $PYENV_NAME; 

# i do this in a subshell because i think maybe it prevents me from doing a CD in my 
# actual real terminal.
$(
    cd $DIR; # Enter the jobs dir first
    python $@
)